# Propriedades da aplicacao Spring Boot
spring:
  main:
    banner-mode: console
  application:
    name: consumer
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

# Configuracao da aplicacao
application:
  backing-services:
    kafka:
      bootstrap-servers: localhost:9092
      dev-operation-topic: dev-operation-topic
      dev-status-topic: dev-status-topic
    database:
      url: jdbc:h2:mem:dev;DB_CLOSE_DELAY=-1
      username: sa
      password:
      pool-size: 20
      driver-class-name: org.h2.Driver

# Server
server:
  port: 8082
  servlet:
    context-path: /consumer

# Configuracao do banco de dados
spring.jpa:
  show-sql: true
  generate-ddl: true
  database: H2
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
  defer-datasource-initialization: true
