# Application properties Spring Boot
spring:
  main:
    banner-mode: console
  application:
    name: processor

# Application configuration
application:
  backing-services:
    kafka:
      bootstrap-servers: localhost:9092
      dev-operation-topic: dev-operation-topic
      dev-status-topic: dev-status-topic

# Server
server:
  port: 8081
  servlet:
    context-path: /processor