# Application properties Spring Boot
spring:
  main:
    banner-mode: console
  application:
    name: producer

# Application configuration
application:
  backing-services:
    kafka:
      bootstrap-servers: localhost:9092
      dev-operation-topic: dev-operation-topic

# Server
server:
  port: 8080
  servlet:
    context-path: /producer